# This is a basic workflow to help you get started with Actions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
name: Python Using Anaconda

on: [push]

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
      - run: conda info
      - run: conda list
      - run: conda config --show
