# This is a basic workflow to help you get started with Actions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
name: Python Using Anaconda

on: [push]

jobs:
  caching-example:
    name: Caching
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-activate-base: false
          channel-priority: strict
          environment-file: environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: conda env list
      - name: check Sphinx
        shell: bash -l {0}
        run: conda list sphinx
      - name: Build sphinx
        shell: bash -l {0}
        run: sphinx-build -b html source _build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _build # The folder the action should deploy.
